// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHXlRgWkLETxjoo_WeD6vHjHRwleLtiH4',
    appId: '1:792259680505:web:95a7ae32d41e7a51cc2a28',
    messagingSenderId: '792259680505',
    projectId: 'initialtest-73d22',
    authDomain: 'initialtest-73d22.firebaseapp.com',
    storageBucket: 'initialtest-73d22.firebasestorage.app',
    measurementId: 'G-832TBZCVJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6GJvxYWnihPP6VcgDZTnXgCy79exPo4',
    appId: '1:792259680505:android:3db4b85efdcd66c5cc2a28',
    messagingSenderId: '792259680505',
    projectId: 'initialtest-73d22',
    storageBucket: 'initialtest-73d22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBevrxUHH7EM6pGLEnFC1_zi2Y0B8MSHxs',
    appId: '1:792259680505:ios:ac2e8565aed4ff35cc2a28',
    messagingSenderId: '792259680505',
    projectId: 'initialtest-73d22',
    storageBucket: 'initialtest-73d22.firebasestorage.app',
    iosBundleId: 'com.example.initialTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBevrxUHH7EM6pGLEnFC1_zi2Y0B8MSHxs',
    appId: '1:792259680505:ios:ac2e8565aed4ff35cc2a28',
    messagingSenderId: '792259680505',
    projectId: 'initialtest-73d22',
    storageBucket: 'initialtest-73d22.firebasestorage.app',
    iosBundleId: 'com.example.initialTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHXlRgWkLETxjoo_WeD6vHjHRwleLtiH4',
    appId: '1:792259680505:web:de3a6a9ed98df9d7cc2a28',
    messagingSenderId: '792259680505',
    projectId: 'initialtest-73d22',
    authDomain: 'initialtest-73d22.firebaseapp.com',
    storageBucket: 'initialtest-73d22.firebasestorage.app',
    measurementId: 'G-82HHRBEFT0',
  );
}
